### ISSUE TITLE
Error running parallel on slurm cluster

### ISSUE THREAD

**Issue by maclines** [cma2015/G2P#1]
I received the following error running g2p in parallel on a slurm cluster: 

Error in checkForRemoteErrors(val) : 
  5 nodes produced errors; first error: unused argument (n.cores = cpus)
Calls: G2PCrossValidation ... clusterApplyLB -> dynamicClusterApply -> checkForRemoteErrors
Execution halted

I was unable to find the argument n.cores in any of the code. Any ideas on a possible cause?

**Comment by qchengray** [comment]
I am sorry that you have encountered this problem. The changes of package "sommer" caused this error, the function "mmer" in latest version"sommer" have remove the parameter “n.cores”. So we advise you not to use the method AI NR EM and EMMA temporarily. 
We will release a new version as soon as possible to solve this problem. 
Thanks for your attention.

**Comment by qchengray** [comment]
I am sorry that you have encountered this problem. The changes of package "sommer" caused this error, the function "mmer" in latest version"sommer" have remove the parameter “n.cores”. So we advise you not to use the method AI NR EM and EMMA temporarily.
We will release a new version as soon as possible to solve this problem.
Thanks for your attention.
