### ISSUE TITLE
GYSS complete dataset can not be downloaded

### ISSUE THREAD

**Issue by pjx1990** [cma2015/G2P#4]
GYSS complete dataset could not be downloaded with 242 samples and 46373 SNPs. The hyperlink is false.

**Comment by qchengray** [comment]
> GYSS complete dataset could not be downloaded with 242 samples and 46373 SNPs. The hyperlink is false.
Thanks for your attention on our project. This corresponding full data came from paper named "Genomic-enabled prediction with classification algorithms" published in 2014. And the data could been found and downloaded from https://repository.cimmyt.org/xmlui/handle/10883/2976. Hope this answer can help you.
